spring.application.name=nutri
spring.jpa.hibernate.ddl-auto=update

management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health,prometheus

# ?? ???? (?? ???? ????? ??)
spring.profiles.active=local